import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 0,
    name: 'Brasil 2026/27 - Jogador',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    originalPrice: 'R$ 229,90',
    icon: '🇧🇷',
    bg: 'linear-gradient(135deg,#003018,#006B2D)',
    images: ['/products/brasil-home-foto1.png', '/products/brasil-home-foto2.png', '/products/brasil-home-foto3.png', '/products/brasil-home-foto4.png'],
    desc: 'A nova camisa da Seleção Brasileira para a Copa do Mundo 2026. Modelo jogador premium com toda a tecnologia e o orgulho verde e amarelo.',
    filter: 'selecao',
    active: true,
    stock: { M: 2, G: 2 },
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 1,
    name: 'Brasil 2026/27 - Jogador',
    label: 'Away',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    originalPrice: 'R$ 229,90',
    icon: '⚫',
    bg: 'linear-gradient(135deg,#0a0f2e,#001a5e)',
    images: ['/products/brasil-away-foto1.png', '/products/brasil-away-foto2.png', '/products/brasil-away-foto3.png', '/products/brasil-away-foto4.png', '/products/brasil-away-foto5.png'],
    desc: 'A camisa alternativa da Seleção Brasileira para 2026. Design arrojado e moderno para representar o Brasil de um ângulo diferente.',
    filter: 'selecao',
    active: true,
    stock: { M: 2, G: 2 },
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 2,
    name: 'REAL MADRID',
    label: '2024/25',
    cat: 'Clube · La Liga · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '⚪',
    bg: 'linear-gradient(135deg,#0a0a1a,#111128)',
    desc: 'O clube mais vitorioso do mundo. Camisa do Real Madrid com o clássico branco imaculado em modelo jogador Adidas.',
    filter: 'clube',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'La Liga' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 3,
    name: 'MANCHESTER CITY',
    label: '2024/25',
    cat: 'Clube · Premier League · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🔵',
    bg: 'linear-gradient(135deg,#001a3a,#003570)',
    desc: 'A dominante equipe de Guardiola com seu azul celeste característico. Modelo jogador Puma com acabamento premium.',
    filter: 'clube',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'Premier League' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 4,
    name: 'ARGENTINA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇦🇷',
    bg: 'linear-gradient(135deg,#001a3a,#004080)',
    images: ['/products/arg-home-foto1.png', '/products/arg-home-foto2.png', '/products/arg-home-foto3.png', '/products/arg-home-foto4.png'],
    desc: 'As listras albicelestes de Messi para a defesa do título mundial. Camisa oficial Argentina 2026 modelo jogador.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 5,
    name: 'BARCELONA',
    label: '2024/25',
    cat: 'Clube · La Liga · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🔴',
    bg: 'linear-gradient(135deg,#1a0010,#3a0020)',
    desc: 'Clássico e atemporal. A camisa do Barça com as tradicionais listras blaugrana em modelo jogador Nike.',
    filter: 'clube',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'La Liga' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 6,
    name: 'PSG',
    label: '2024/25',
    cat: 'Clube · Ligue 1 · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🔷',
    bg: 'linear-gradient(135deg,#000818,#001530)',
    desc: 'O clube mais glamouroso da Europa. Camisa do Paris Saint-Germain com design fashion-forward.',
    filter: 'clube',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'Ligue 1' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 7,
    name: 'PORTUGAL 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇵🇹',
    bg: 'linear-gradient(135deg,#1a0005,#3a0010)',
    images: ['/products/pt-home-foto1.png', '/products/pt-home-foto2.png', '/products/pt-home-foto3.png'],
    desc: 'Vermelho e verde da nação portuguesa. Portugal para a Copa 2026 com CR7 e a nova geração.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 8,
    name: 'ALEMANHA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇩🇪',
    bg: 'linear-gradient(135deg,#0a0a0a,#1a1a1a)',
    images: ['/products/de-home-foto1.png', '/products/de-home-foto2.png', '/products/de-home-foto3.png'],
    desc: 'O clássico branco alemão de volta às grandes competições. Alemanha 2026 com o rigor e precisão que só a Mannschaft tem.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 9,
    name: 'COLÔMBIA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇨🇴',
    bg: 'linear-gradient(135deg,#1a1400,#3a2e00)',
    desc: 'O amarelo vibrante da Colômbia com James Rodríguez à frente. Uma das seleções mais elegantes da Copa 2026.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 10,
    name: 'INGLATERRA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    bg: 'linear-gradient(135deg,#0a0a1a,#001030)',
    desc: 'A camisa dos Três Leões para conquistar o mundo em 2026. Inglaterra com Bellingham liderando a nova geração.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 11,
    name: 'FRANÇA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇫🇷',
    bg: 'linear-gradient(135deg,#00052e,#001080)',
    desc: 'Les Bleus com Mbappé em busca do tri. A camisa azul da França é uma das mais icônicas do futebol mundial.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 12,
    name: 'ESPANHA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇪🇸',
    bg: 'linear-gradient(135deg,#1a0000,#550000)',
    desc: 'A Roja defensora do título europeu chega para a Copa 2026 com Yamal e Pedri reinventando o futebol.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 13,
    name: 'BÉLGICA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇧🇪',
    bg: 'linear-gradient(135deg,#1a0000,#3a0000)',
    desc: 'Os Diabos Vermelhos com De Bruyne em sua última dança mundial. Bélgica 2026 com o vermelho que marca.',
    filter: 'selecao',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
];
