import { Product } from '@/types';

export const products: Product[] = [
  // ── SELEÇÕES ATIVAS ────────────────────────────────────────────────
  {
    id: 0,
    slug: 'brasil-2026-home',
    name: 'Brasil 2026/27',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    originalPrice: 'R$ 229,90',
    icon: '🇧🇷',
    bg: 'linear-gradient(135deg,#003018,#006B2D)',
    images: ['/products/brasil-home-foto1.png', '/products/brasil-home-foto2.png', '/products/brasil-home-foto3.png', '/products/brasil-home-foto4.png'],
    desc: 'A nova camisa da Seleção Brasileira para a Copa do Mundo 2026. Modelo jogador premium com toda a tecnologia Nike e o orgulho verde e amarelo.',
    filter: 'selecao',
    category: 'selecoes',
    active: true,
    stock: { M: 2, G: 2 },
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 1,
    slug: 'brasil-2026-away',
    name: 'Brasil 2026/27',
    label: 'Away',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    originalPrice: 'R$ 229,90',
    icon: '⚫',
    bg: 'linear-gradient(135deg,#0a0f2e,#001a5e)',
    images: ['/products/brasil-away-foto1.png', '/products/brasil-away-foto2.png', '/products/brasil-away-foto3.png', '/products/brasil-away-foto4.png', '/products/brasil-away-foto5.png'],
    desc: 'A camisa alternativa da Seleção Brasileira para 2026. Design arrojado e moderno para representar o Brasil de um ângulo diferente.',
    filter: 'selecao',
    category: 'selecoes',
    active: true,
    stock: { M: 2, G: 2 },
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },

  // ── SELEÇÕES EM BREVE ──────────────────────────────────────────────
  {
    id: 4,
    slug: 'argentina-2026-home',
    name: 'Argentina 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇦🇷',
    bg: 'linear-gradient(135deg,#001a3a,#004080)',
    images: ['/products/arg-home-foto1.png', '/products/arg-home-foto2.png', '/products/arg-home-foto3.png', '/products/arg-home-foto4.png'],
    desc: 'As listras albicelestes de Messi para a defesa do título mundial. Camisa oficial Argentina 2026 modelo jogador.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 7,
    slug: 'portugal-2026-home',
    name: 'Portugal 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇵🇹',
    bg: 'linear-gradient(135deg,#1a0005,#3a0010)',
    images: ['/products/pt-home-foto1.png', '/products/pt-home-foto2.png', '/products/pt-home-foto3.png'],
    desc: 'Vermelho e verde da nação portuguesa. Portugal para a Copa 2026 com CR7 e a nova geração.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 8,
    slug: 'alemanha-2026-home',
    name: 'Alemanha 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇩🇪',
    bg: 'linear-gradient(135deg,#0a0a0a,#1a1a1a)',
    images: ['/products/de-home-foto1.png', '/products/de-home-foto2.png', '/products/de-home-foto3.png'],
    desc: 'O clássico branco alemão de volta às grandes competições. Alemanha 2026 com o rigor e precisão que só a Mannschaft tem.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 9,
    slug: 'colombia-2026-home',
    name: 'Colômbia 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇨🇴',
    bg: 'linear-gradient(135deg,#1a1400,#3a2e00)',
    desc: 'O amarelo vibrante da Colômbia com James Rodríguez à frente. Uma das seleções mais elegantes da Copa 2026.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 10,
    slug: 'inglaterra-2026-home',
    name: 'Inglaterra 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    bg: 'linear-gradient(135deg,#0a0a1a,#001030)',
    desc: 'A camisa dos Três Leões para conquistar o mundo em 2026. Inglaterra com Bellingham liderando a nova geração.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 11,
    slug: 'franca-2026-home',
    name: 'França 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇫🇷',
    bg: 'linear-gradient(135deg,#00052e,#001080)',
    desc: 'Les Bleus com Mbappé em busca do tri. A camisa azul da França é uma das mais icônicas do futebol mundial.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 12,
    slug: 'espanha-2026-home',
    name: 'Espanha 2026',
    label: 'Home',
    cat: 'Seleção · Copa 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇪🇸',
    bg: 'linear-gradient(135deg,#1a0000,#550000)',
    desc: 'A Roja defensora do título europeu chega para a Copa 2026 com Yamal e Pedri reinventando o futebol.',
    filter: 'selecao',
    category: 'selecoes',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },

  // ── TIMES BRASILEIROS EM BREVE ─────────────────────────────────────
  {
    id: 20,
    slug: 'gremio-2025',
    name: 'Grêmio',
    label: '2025',
    cat: 'Time Brasileiro · Série A · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🔵',
    bg: 'linear-gradient(135deg,#00061a,#001560)',
    desc: 'O Imortal Tricolor Gaúcho. Camisa do Grêmio 2025 em modelo jogador, para os torcedores que levam o futebol a sério.',
    filter: 'clube',
    category: 'times-br',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 21,
    slug: 'internacional-2025',
    name: 'Internacional',
    label: '2025',
    cat: 'Time Brasileiro · Série A · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🔴',
    bg: 'linear-gradient(135deg,#1a0000,#500000)',
    desc: 'O Colorado do povo gaúcho. Camisa do Internacional 2025, vermelho e paixão em modelo jogador premium.',
    filter: 'clube',
    category: 'times-br',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 2,
    slug: 'real-madrid-2425',
    name: 'Real Madrid',
    label: '2024/25',
    cat: 'Clube · La Liga · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '⚪',
    bg: 'linear-gradient(135deg,#0a0a1a,#111128)',
    desc: 'O clube mais vitorioso do mundo. Camisa do Real Madrid com o clássico branco imaculado em modelo jogador Adidas.',
    filter: 'clube',
    category: 'times-br',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'La Liga' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 3,
    slug: 'manchester-city-2425',
    name: 'Manchester City',
    label: '2024/25',
    cat: 'Clube · Premier League · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🩵',
    bg: 'linear-gradient(135deg,#001a3a,#003570)',
    desc: 'A dominante equipe de Guardiola com seu azul celeste característico. Modelo jogador Puma com acabamento premium.',
    filter: 'clube',
    category: 'times-br',
    active: false,
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'Premier League' },
      { key: 'Origem', val: 'Importado' },
    ],
  },

  // ── RETRÔS EM BREVE ───────────────────────────────────────────────
  {
    id: 30,
    slug: 'brasil-1970-retro',
    name: 'Brasil 1970',
    label: 'Retrô',
    cat: 'Seleção · Copa 1970 · Retrô Premium',
    badge: 'retro',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇧🇷',
    bg: 'linear-gradient(135deg,#1a1000,#3a2500)',
    desc: 'A camisa mais icônica da história do futebol. Brasil 1970 com Pelé, a geração que conquistou o mundo três vezes. Retrô premium bordado.',
    filter: 'selecao',
    category: 'retro',
    active: false,
    specs: [
      { key: 'Versão', val: 'Retrô Premium' },
      { key: 'Bordado', val: 'Sim' },
      { key: 'Ano', val: '1970 · México' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 31,
    slug: 'brasil-1994-retro',
    name: 'Brasil 1994',
    label: 'Retrô',
    cat: 'Seleção · Copa 1994 · Retrô Premium',
    badge: 'retro',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🏆',
    bg: 'linear-gradient(135deg,#0f1a00,#1a3000)',
    desc: 'O tetra de Romário e Bebeto. Brasil 1994 com o icônico design Umbro que marcou uma geração. Retrô premium com bordado.',
    filter: 'selecao',
    category: 'retro',
    active: false,
    specs: [
      { key: 'Versão', val: 'Retrô Premium' },
      { key: 'Bordado', val: 'Sim' },
      { key: 'Ano', val: '1994 · EUA' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 32,
    slug: 'brasil-2002-retro',
    name: 'Brasil 2002',
    label: 'Retrô',
    cat: 'Seleção · Copa 2002 · Retrô Premium',
    badge: 'retro',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '⭐',
    bg: 'linear-gradient(135deg,#1a0a00,#3a1500)',
    desc: 'O pentacampeonato de Ronaldo Fenômeno. Brasil 2002 com o inconfundível amarelo Nike que entrou para a história.',
    filter: 'selecao',
    category: 'retro',
    active: false,
    specs: [
      { key: 'Versão', val: 'Retrô Premium' },
      { key: 'Bordado', val: 'Sim' },
      { key: 'Ano', val: '2002 · Japão/Coreia' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
];
