import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 0,
    name: 'Brasil 2026/27 - Jogador',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '🇧🇷',
    bg: 'linear-gradient(135deg,#003018,#006B2D)',
    desc: 'A nova camisa da Seleção Brasileira para a Copa do Mundo 2026. Modelo jogador premium com toda a tecnologia e o orgulho verde e amarelo.',
    filter: 'selecao',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 1,
    name: 'Brasil 2026/27 - Jogador',
    label: 'Away',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 189,90',
    priceNum: 18990,
    icon: '⚫',
    bg: 'linear-gradient(135deg,#0a0f2e,#001a5e)',
    images: ['/products/brasil-away-front.jpg', '/products/brasil-away-back.jpg'],
    desc: 'A camisa alternativa da Seleção Brasileira para 2026. Design arrojado e moderno para representar o Brasil de um ângulo diferente.',
    filter: 'selecao',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Nike Aero-FIT' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 2,
    name: 'REAL MADRID',
    label: '2024/25',
    cat: 'Clube · La Liga · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 349,90',
    priceNum: 34990,
    icon: '⚪',
    bg: 'linear-gradient(135deg,#0a0a1a,#111128)',
    desc: 'O clube mais vitorioso do mundo. Camisa do Real Madrid com o clássico branco imaculado em modelo jogador Adidas.',
    filter: 'clube',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'La Liga' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 3,
    name: 'MANCHESTER CITY',
    label: '2024/25',
    cat: 'Clube · Premier League · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 349,90',
    priceNum: 34990,
    icon: '🔵',
    bg: 'linear-gradient(135deg,#001a3a,#003570)',
    desc: 'A dominante equipe de Guardiola com seu azul celeste característico. Modelo jogador Puma com acabamento premium.',
    filter: 'clube',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'Premier League' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 4,
    name: 'ARGENTINA 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 379,90',
    priceNum: 37990,
    icon: '🇦🇷',
    bg: 'linear-gradient(135deg,#001a3a,#004080)',
    desc: 'As listras albicelestes de Messi para a defesa do título mundial. Camisa oficial Argentina 2026 modelo jogador.',
    filter: 'selecao',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'HEAT.RDY' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 5,
    name: 'BARCELONA',
    label: '2024/25',
    cat: 'Clube · La Liga · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 349,90',
    priceNum: 34990,
    icon: '🔴',
    bg: 'linear-gradient(135deg,#1a0010,#3a0020)',
    desc: 'Clássico e atemporal. A camisa do Barça com as tradicionais listras blaugrana em modelo jogador Nike.',
    filter: 'clube',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'La Liga' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 6,
    name: 'PSG',
    label: '2024/25',
    cat: 'Clube · Ligue 1 · Modelo Jogador',
    badge: 'jogador',
    price: 'R$ 349,90',
    priceNum: 34990,
    icon: '🔷',
    bg: 'linear-gradient(135deg,#000818,#001530)',
    desc: 'O clube mais glamouroso da Europa. Camisa do Paris Saint-Germain com design fashion-forward.',
    filter: 'clube',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Liga', val: 'Ligue 1' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
  {
    id: 7,
    name: 'PORTUGAL 2026',
    label: 'Home',
    cat: 'Seleção · Copa do Mundo 2026 · Modelo Jogador',
    badge: 'novo',
    price: 'R$ 379,90',
    priceNum: 37990,
    icon: '🇵🇹',
    bg: 'linear-gradient(135deg,#1a0005,#3a0010)',
    desc: 'Vermelho e verde da nação portuguesa. Portugal para a Copa 2026 com CR7 e a nova geração.',
    filter: 'selecao',
    specs: [
      { key: 'Versão', val: 'Modelo Jogador' },
      { key: 'Material', val: '100% Poliéster' },
      { key: 'Tecnologia', val: 'Dri-FIT ADV' },
      { key: 'Origem', val: 'Importado' },
    ],
  },
];
